const $=s=>document.querySelector(s);const state={workspaces:[],current:null,tasks:[]};const lanes=[['backlog','Backlog'],['ready','Ready'],['in-progress','In motion'],['review','Review'],['done','Done']];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function json(path){const r=await fetch(path,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.json()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('is-visible');setTimeout(()=>el.classList.remove('is-visible'),2200)}
function group(status){if(status==='blocked')return'backlog';if(status==='verification')return'review';return status}
function render(){const w=state.current||{};const counts={};state.tasks.forEach(t=>counts[group(t.status)]=(counts[group(t.status)]||0)+1);$('#workspace-title').textContent=w.label||'Workspace overview';$('#workspace-goal').textContent=w.goal||'No goal has been recorded yet.';$('#workspace-purpose').textContent=w.purpose||'A quiet view of what is moving and what needs intervention.';$('#metric-open').textContent=state.tasks.filter(t=>!['done','cancelled'].includes(t.status)).length;$('#metric-active').textContent=counts['in-progress']||0;$('#metric-review').textContent=counts.review||0;$('#metric-done').textContent=counts.done||0;$('#workspace-meta').innerHTML=`<div><dt>Identity</dt><dd>${esc(w.workspace_id||'—')}</dd></div><div><dt>State</dt><dd>${esc(w.status||'—')}</dd></div><div><dt>Bounded surfaces</dt><dd>${(w.artifact_roots||[]).map(esc).join(' · ')||'Not declared'}</dd></div>`;$('#task-board').innerHTML=lanes.map(([key,label])=>{const tasks=state.tasks.filter(t=>group(t.status)===key);return`<section class="lane"><div class="lane-head"><span>${label}</span><span class="count">${tasks.length}</span></div><div class="cards">${tasks.length?tasks.map(t=>`<article class="task"><span class="task-id">${esc(t.task_id)}</span><h3>${esc(t.title)}</h3><small>${esc(t.status)}</small></article>`).join(''):'<p class="empty">Nothing rests here.</p>'}</div></section>`}).join('')}
async function select(id){state.current=state.workspaces.find(w=>w.workspace_id===id)||null;if(!state.current){state.tasks=[];render();return}state.tasks=(await json(`/api/workspaces/${encodeURIComponent(id)}/tasks`)).tasks||[];render()}
async function load(){try{const health=await json('/health');$('#health-dot').classList.toggle('is-live',health.status==='ok');$('#health-label').textContent=health.status==='ok'?'healthy':'degraded';state.workspaces=(await json('/api/workspaces')).workspaces||[];const selectEl=$('#workspace-select');const previous=state.current?.workspace_id;selectEl.innerHTML=state.workspaces.length?state.workspaces.map(w=>`<option value="${esc(w.workspace_id)}">${esc(w.label||w.workspace_id)}</option>`).join(''):'<option>No workspaces</option>';const id=state.workspaces.some(w=>w.workspace_id===previous)?previous:state.workspaces[0]?.workspace_id;selectEl.value=id||'';await select(id);toast('Workspace refreshed')}catch(e){$('#health-label').textContent='unavailable';toast(e.message)}}
$('#workspace-select').addEventListener('change',e=>select(e.target.value));$('#refresh').addEventListener('click',load);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');document.querySelector(b.dataset.view==='guardrails'?'.guard-card':b.dataset.view==='work'?'.work-panel':'.metrics')?.scrollIntoView({behavior:'smooth',block:'start'})}));load();
