"""Provider-neutral factual code-graph domain contracts.

Must not import application, storage, adapters, sqlite3, HTTP, MCP, or
extractor provider SDKs.
"""

from __future__ import annotations

from holodeck_governance.domain.workspace.intelligence.code_graph.entities import (
    CodeEntityFact,
    build_entity_key,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.extractors import (
    UNRESOLVED_DYNAMIC_CALL,
    assert_entity_catalog_closed,
    assert_extraction_candidates_conform,
    assert_no_fabricated_dynamic_call_edges,
    assert_relation_catalog_closed,
    relation_kinds_covered,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.incremental import (
    IncrementalMergeStats,
    IncrementalRefreshPlan,
    NormalizedSnapshotFacts,
    compare_normalized_snapshots,
    merge_incremental_facts,
    plan_incremental_refresh,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.paths import (
    normalize_repository_relative_path,
    require_immutable_repository_revision,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.queries import (
    ChangeNeighborhoodResult,
    CompareSnapshotsResult,
    EntityHit,
    FindEntitiesResult,
    GetEntityResult,
    GraphPath,
    GraphPathStep,
    NeighborHit,
    NeighborsResult,
    ProvenanceHit,
    QueryBudget,
    QueryCoverage,
    QueryOmissions,
    SourcesForFactsResult,
    TraversalDirection,
    TraversePathsResult,
    change_neighborhood_paths,
    compare_snapshots_facts,
    coverage_from_snapshot,
    filter_entities,
    neighbors_of,
    sources_for_facts,
    traverse_paths,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.relations import (
    CodeRelationFact,
    build_relation_key,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.sentinels import (
    SentinelCatalog,
    SentinelFinding,
    SentinelKind,
    SentinelStatus,
    evaluate_sentinels,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.snapshots import (
    ExtractionDiagnostic,
    ExtractionLimits,
    RepositoryExtractionRun,
    RepositoryGraphSnapshot,
    assert_relation_endpoints_resolve,
    assert_snapshot_counts_match,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.spans import (
    SourceSpan,
)
from holodeck_governance.domain.workspace.intelligence.code_graph.types import (
    CODE_ENTITY_FACT_SCHEMA_VERSION,
    CODE_GRAPH_SCHEMA_VERSION,
    CODE_RELATION_FACT_SCHEMA_VERSION,
    ENTITY_KEY_SCHEMA_VERSION,
    ENTITY_KIND_CATALOG_VERSION,
    EXTRACTION_RUN_SCHEMA_VERSION,
    GRAPH_SNAPSHOT_SCHEMA_VERSION,
    INITIAL_ENTITY_KINDS,
    INITIAL_RELATION_KINDS,
    RELATION_KEY_SCHEMA_VERSION,
    RELATION_KIND_CATALOG_VERSION,
    CodeGraphReason,
    CoverageStatus,
    EntityKind,
    ExtractionRunStatus,
    ObservationMethod,
    RelationKind,
    SnapshotStatus,
    code_graph_error,
)

__all__ = [
    "CODE_ENTITY_FACT_SCHEMA_VERSION",
    "CODE_GRAPH_SCHEMA_VERSION",
    "CODE_RELATION_FACT_SCHEMA_VERSION",
    "ENTITY_KEY_SCHEMA_VERSION",
    "ENTITY_KIND_CATALOG_VERSION",
    "EXTRACTION_RUN_SCHEMA_VERSION",
    "GRAPH_SNAPSHOT_SCHEMA_VERSION",
    "INITIAL_ENTITY_KINDS",
    "INITIAL_RELATION_KINDS",
    "RELATION_KEY_SCHEMA_VERSION",
    "RELATION_KIND_CATALOG_VERSION",
    "UNRESOLVED_DYNAMIC_CALL",
    "ChangeNeighborhoodResult",
    "CodeEntityFact",
    "CodeGraphReason",
    "CodeRelationFact",
    "CompareSnapshotsResult",
    "CoverageStatus",
    "EntityHit",
    "EntityKind",
    "ExtractionDiagnostic",
    "ExtractionLimits",
    "ExtractionRunStatus",
    "FindEntitiesResult",
    "GetEntityResult",
    "GraphPath",
    "GraphPathStep",
    "IncrementalMergeStats",
    "IncrementalRefreshPlan",
    "NeighborHit",
    "NeighborsResult",
    "NormalizedSnapshotFacts",
    "ObservationMethod",
    "ProvenanceHit",
    "QueryBudget",
    "QueryCoverage",
    "QueryOmissions",
    "RelationKind",
    "RepositoryExtractionRun",
    "RepositoryGraphSnapshot",
    "SentinelCatalog",
    "SentinelFinding",
    "SentinelKind",
    "SentinelStatus",
    "SnapshotStatus",
    "SourceSpan",
    "SourcesForFactsResult",
    "TraversalDirection",
    "TraversePathsResult",
    "assert_entity_catalog_closed",
    "assert_extraction_candidates_conform",
    "assert_no_fabricated_dynamic_call_edges",
    "assert_relation_catalog_closed",
    "assert_relation_endpoints_resolve",
    "assert_snapshot_counts_match",
    "build_entity_key",
    "build_relation_key",
    "change_neighborhood_paths",
    "code_graph_error",
    "compare_normalized_snapshots",
    "compare_snapshots_facts",
    "coverage_from_snapshot",
    "evaluate_sentinels",
    "filter_entities",
    "merge_incremental_facts",
    "neighbors_of",
    "normalize_repository_relative_path",
    "plan_incremental_refresh",
    "relation_kinds_covered",
    "require_immutable_repository_revision",
    "sources_for_facts",
    "traverse_paths",
]
